//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hitachi.Tester.Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Hitachi.Tester.Module", ConfigurationName="ServiceReference1.TesterObjectContract", CallbackContract=typeof(Hitachi.Tester.Client.ServiceReference1.TesterObjectContractCallback))]
    public interface TesterObjectContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/BladeDelFile", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/BladeDelFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BladeDelFileReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BladeDelFileSenderFaultDetailFault", Name="SenderFaultDetail")]
        bool BladeDelFile(string Key, string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/BunnyReInit", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/BunnyReInitResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BunnyReInitSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BunnyReInitReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        bool BunnyReInit();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsType", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetMemsTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsTypeSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsTypeReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void SetMemsType(Hitachi.Tester.Module.BunnyPinMotionType whichKind);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsOpenSensorType", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetMemsOpenSensorTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsOpenSensorTypeSenderFaultDetail" +
            "Fault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsOpenSensorTypeReceiverFaultDeta" +
            "ilFault", Name="ReceiverFaultDetail")]
        void SetMemsOpenSensorType(Hitachi.Tester.Module.BunnyPinMotionSensor whichKind);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsCloseSensorType", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetMemsCloseSensorTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsCloseSensorTypeSenderFaultDetai" +
            "lFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsCloseSensorTypeReceiverFaultDet" +
            "ailFault", Name="ReceiverFaultDetail")]
        void SetMemsCloseSensorType(Hitachi.Tester.Module.BunnyPinMotionSensor whichKind);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/PinMotionToggle", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/PinMotionToggleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PinMotionToggleSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PinMotionToggleReceiverFaultDetailFaul" +
            "t", Name="ReceiverFaultDetail")]
        void PinMotionToggle();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetRampValue", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetRampValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetRampValueSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetRampValueReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void SetRampValue(string Key, uint value);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/hgst_set_save_servo", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/hgst_set_save_servoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_set_save_servoSenderFaultDetailFa" +
            "ult", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_set_save_servoReceiverFaultDetail" +
            "Fault", Name="ReceiverFaultDetail")]
        void hgst_set_save_servo(int index, int dev, int type, int open_end_pos, int open_max_vel, int open_accel, int close_end_pos, int close_max_vel, int close_accel, int current_end_pos, int current_max_vel, int current_accel);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/hgst_get_neutral", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/hgst_get_neutralResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_get_neutralSenderFaultDetailFault" +
            "", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_get_neutralReceiverFaultDetailFau" +
            "lt", Name="ReceiverFaultDetail")]
        void hgst_get_neutral(int index, int dev);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/hgst_set_neutral", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/hgst_set_neutralResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_set_neutralSenderFaultDetailFault" +
            "", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_set_neutralReceiverFaultDetailFau" +
            "lt", Name="ReceiverFaultDetail")]
        void hgst_set_neutral(int index, int dev, int i_neutral);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/hgst_get_servo", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/hgst_get_servoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_get_servoSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_get_servoReceiverFaultDetailFault" +
            "", Name="ReceiverFaultDetail")]
        void hgst_get_servo(int index, int dev);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/hgst_move_servo", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/hgst_move_servoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_move_servoSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_move_servoReceiverFaultDetailFaul" +
            "t", Name="ReceiverFaultDetail")]
        void hgst_move_servo(int index, int dev, int type, int end_pos, int max_vel, int accel);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/hgst_usb_reset", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/hgst_usb_resetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_usb_resetSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_usb_resetReceiverFaultDetailFault" +
            "", Name="ReceiverFaultDetail")]
        void hgst_usb_reset(int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetStrings", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetStringsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetStringsSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetStringsReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void SetStrings(string key, string[] names, string[] strings);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetStrings", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetStringsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetStringsReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetStringsSenderFaultDetailFault", Name="SenderFaultDetail")]
        string[] GetStrings(string key, string[] names);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetDataViaEvent", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetDataViaEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetDataViaEventReceiverFaultDetailFaul" +
            "t", Name="ReceiverFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetDataViaEventSenderFaultDetailFault", Name="SenderFaultDetail")]
        void GetDataViaEvent(string[] names);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetIntegers", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetIntegersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetIntegersSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetIntegersReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void SetIntegers(string key, string[] names, int[] numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetIntegers", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetIntegersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetIntegersReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetIntegersSenderFaultDetailFault", Name="SenderFaultDetail")]
        int[] GetIntegers(string key, string[] names);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetTclStart", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetTclStartResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetTclStartReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetTclStartSenderFaultDetailFault", Name="SenderFaultDetail")]
        void SetTclStart(string key, string command);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetTclStart", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetTclStartResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetTclStartSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetTclStartReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        string GetTclStart(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/PauseEvents", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/PauseEventsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PauseEventsSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PauseEventsReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void PauseEvents(bool bwait);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/PauseTests", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/PauseTestsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PauseTestsSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PauseTestsReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void PauseTests(bool bwait);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/BladeFilePath", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/BladeFilePathResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BladeFilePathSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BladeFilePathReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        string BladeFilePath();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/FactFilePath", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/FactFilePathResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/FactFilePathSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/FactFilePathReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        string FactFilePath();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GradeFilePath", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GradeFilePathResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GradeFilePathSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GradeFilePathReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        string GradeFilePath();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/FirmwareFilePath", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/FirmwareFilePathResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/FirmwareFilePathReceiverFaultDetailFau" +
            "lt", Name="ReceiverFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/FirmwareFilePathSenderFaultDetailFault" +
            "", Name="SenderFaultDetail")]
        string FirmwareFilePath();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/CountsFilePath", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/CountsFilePathResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/CountsFilePathReceiverFaultDetailFault" +
            "", Name="ReceiverFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/CountsFilePathSenderFaultDetailFault", Name="SenderFaultDetail")]
        string CountsFilePath();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/LogInValue", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/LogInValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/LogInValueReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/LogInValueSenderFaultDetailFault", Name="SenderFaultDetail")]
        void LogInValue(int setValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/Connect", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/ConnectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/ConnectSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/ConnectReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        uint Connect(string UserID, string Password, string ComputerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/Initialize", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/InitializeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/InitializeReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/InitializeSenderFaultDetailFault", Name="SenderFaultDetail")]
        void Initialize(string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/Ping", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/PingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PingReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PingSenderFaultDetailFault", Name="SenderFaultDetail")]
        string Ping(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/Disconnect", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/DisconnectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/DisconnectSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/DisconnectReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void Disconnect(string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/Abort", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/AbortResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/AbortSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/AbortReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        bool Abort(string Reason, bool Force);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/StartTest", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/StartTestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/StartTestSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/StartTestReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void StartTest(string ParseString, string TestName, string GradeName, string tableStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetConfig", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetConfigResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetConfigSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetConfigReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void SetConfig(string NewConfig);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetConfig", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetConfigResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetConfigSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetConfigReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void GetConfig(string TestName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/DelConfig", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/DelConfigResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/DelConfigSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/DelConfigReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        bool DelConfig(string Key, string TestName);
        
//         [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/DirConfig", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/DirConfigResponse")]
//         [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/DirConfigReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
//         [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/DirConfigSenderFaultDetailFault", Name="SenderFaultDetail")]
//         Hitachi.Tester.Module.FileNameStruct[] DirConfig(string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/CopyFileOnBlade", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/CopyFileOnBladeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/CopyFileOnBladeSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/CopyFileOnBladeReceiverFaultDetailFaul" +
            "t", Name="ReceiverFaultDetail")]
        bool CopyFileOnBlade(string fromFile, string toFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetConfigCRC", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetConfigCRCResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetConfigCRCSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetConfigCRCReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        string GetConfigCRC(string TestName);
        
//         [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetGradeCRCs", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetGradeCRCsResponse")]
//         [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetGradeCRCsReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
//         [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetGradeCRCsSenderFaultDetailFault", Name="SenderFaultDetail")]
//         Hitachi.Tester.Module.FileNameStruct GetGradeCRCs(string TestName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetFileCRC", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetFileCRCResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetFileCRCSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetFileCRCReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        string GetFileCRC(string TestName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/TclInput", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/TclInputResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/TclInputSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/TclInputReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void TclInput(string inputString, bool bToTv);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/TclCommand", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/TclCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/TclCommandSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/TclCommandReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void TclCommand(string Command, bool bToTv);
        
//         [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetModuleState", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetModuleStateResponse")]
//         [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetModuleStateSenderFaultDetailFault", Name="SenderFaultDetail")]
//         [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetModuleStateReceiverFaultDetailFault" +
//             "", Name="ReceiverFaultDetail")]
//         Hitachi.Tester.Module.TesterStateStruct GetModuleState();
        
//         [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetModuleState", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetModuleStateResponse")]
//         [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetModuleStateSenderFaultDetailFault", Name="SenderFaultDetail")]
//         [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetModuleStateReceiverFaultDetailFault" +
//             "", Name="ReceiverFaultDetail")]
//         void SetModuleState(Hitachi.Tester.Module.TesterStateStruct testerState);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetBunnyStatus", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetBunnyStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetBunnyStatusSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetBunnyStatusReceiverFaultDetailFault" +
            "", Name="ReceiverFaultDetail")]
        void GetBunnyStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetMemsState", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetMemsStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetMemsStateReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetMemsStateSenderFaultDetailFault", Name="SenderFaultDetail")]
        Hitachi.Tester.Enums.MemsStateValues GetMemsState();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetCounts", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetCountsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetCountsSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetCountsReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void SetCounts(string countsString);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetCountValue", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetCountValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetCountValueSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetCountValueReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        int GetCountValue(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetCountValue", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetCountValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetCountValueSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetCountValueReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void SetCountValue(string name, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/IncCountValue", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/IncCountValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/IncCountValueSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/IncCountValueReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void IncCountValue(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SaveCounts", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SaveCountsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SaveCountsSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SaveCountsReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void SaveCounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/ZeroCounts", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/ZeroCountsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/ZeroCountsSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/ZeroCountsReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void ZeroCounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/ClearStats", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/ClearStatsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/ClearStatsSenderFaultDetailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/ClearStatsReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
        void ClearStats();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/UpdateStatValuesViaEvent", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/UpdateStatValuesViaEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/UpdateStatValuesViaEventReceiverFaultD" +
            "etailFault", Name="ReceiverFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/UpdateStatValuesViaEventSenderFaultDet" +
            "ailFault", Name="SenderFaultDetail")]
        void UpdateStatValuesViaEvent(string[] what, long from, long to);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetFirstLastIndexViaEvent", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetFirstLastIndexViaEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetFirstLastIndexViaEventSenderFaultDe" +
            "tailFault", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetFirstLastIndexViaEventReceiverFault" +
            "DetailFault", Name="ReceiverFaultDetail")]
        void GetFirstLastIndexViaEvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetFromToViaEvent", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetFromToViaEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetFromToViaEventSenderFaultDetailFaul" +
            "t", Name="SenderFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetFromToViaEventReceiverFaultDetailFa" +
            "ult", Name="ReceiverFaultDetail")]
        void GetFromToViaEvent(long from, long to);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/UpdateDgrValuesViaEvent", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/UpdateDgrValuesViaEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/UpdateDgrValuesViaEventReceiverFaultDe" +
            "tailFault", Name="ReceiverFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/UpdateDgrValuesViaEventSenderFaultDeta" +
            "ilFault", Name="SenderFaultDetail")]
        void UpdateDgrValuesViaEvent(System.TimeSpan timeSpan);
        
//         [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/BladeFileDir", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/BladeFileDirResponse")]
//         [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BladeFileDirSenderFaultDetailFault", Name="SenderFaultDetail")]
//         [System.ServiceModel.FaultContractAttribute(typeof(Hitachi.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BladeFileDirReceiverFaultDetailFault", Name="ReceiverFaultDetail")]
//         Hitachi.Tester.Module.FileNameStruct[] BladeFileDir(string path, string Filter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TesterObjectContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="Hitachi.Tester.Module/TesterObjectContract/BladeEventCallback")]
        void BladeEventCallback(Hitachi.Tester.Module.BladeEventArgs e);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TesterObjectContractChannel : Hitachi.Tester.Client.ServiceReference1.TesterObjectContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TesterObjectContractClient : System.ServiceModel.DuplexClientBase<Hitachi.Tester.Client.ServiceReference1.TesterObjectContract>, Hitachi.Tester.Client.ServiceReference1.TesterObjectContract {
        
        public TesterObjectContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TesterObjectContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TesterObjectContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TesterObjectContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TesterObjectContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool BladeDelFile(string Key, string FileName) {
            return base.Channel.BladeDelFile(Key, FileName);
        }
        
        public bool BunnyReInit() {
            return base.Channel.BunnyReInit();
        }
        
        public void SetMemsType(Hitachi.Tester.Module.BunnyPinMotionType whichKind) {
            base.Channel.SetMemsType(whichKind);
        }
        
        public void SetMemsOpenSensorType(Hitachi.Tester.Module.BunnyPinMotionSensor whichKind) {
            base.Channel.SetMemsOpenSensorType(whichKind);
        }
        
        public void SetMemsCloseSensorType(Hitachi.Tester.Module.BunnyPinMotionSensor whichKind) {
            base.Channel.SetMemsCloseSensorType(whichKind);
        }
        
        public void PinMotionToggle() {
            base.Channel.PinMotionToggle();
        }
        
        public void SetRampValue(string Key, uint value) {
            base.Channel.SetRampValue(Key, value);
        }
        
        public void hgst_set_save_servo(int index, int dev, int type, int open_end_pos, int open_max_vel, int open_accel, int close_end_pos, int close_max_vel, int close_accel, int current_end_pos, int current_max_vel, int current_accel) {
            base.Channel.hgst_set_save_servo(index, dev, type, open_end_pos, open_max_vel, open_accel, close_end_pos, close_max_vel, close_accel, current_end_pos, current_max_vel, current_accel);
        }
        
        public void hgst_get_neutral(int index, int dev) {
            base.Channel.hgst_get_neutral(index, dev);
        }
        
        public void hgst_set_neutral(int index, int dev, int i_neutral) {
            base.Channel.hgst_set_neutral(index, dev, i_neutral);
        }
        
        public void hgst_get_servo(int index, int dev) {
            base.Channel.hgst_get_servo(index, dev);
        }
        
        public void hgst_move_servo(int index, int dev, int type, int end_pos, int max_vel, int accel) {
            base.Channel.hgst_move_servo(index, dev, type, end_pos, max_vel, accel);
        }
        
        public void hgst_usb_reset(int index) {
            base.Channel.hgst_usb_reset(index);
        }
        
        public void SetStrings(string key, string[] names, string[] strings) {
            base.Channel.SetStrings(key, names, strings);
        }
        
        public string[] GetStrings(string key, string[] names) {
            return base.Channel.GetStrings(key, names);
        }
        
        public void GetDataViaEvent(string[] names) {
            base.Channel.GetDataViaEvent(names);
        }
        
        public void SetIntegers(string key, string[] names, int[] numbers) {
            base.Channel.SetIntegers(key, names, numbers);
        }
        
        public int[] GetIntegers(string key, string[] names) {
            return base.Channel.GetIntegers(key, names);
        }
        
        public void SetTclStart(string key, string command) {
            base.Channel.SetTclStart(key, command);
        }
        
        public string GetTclStart(string key) {
            return base.Channel.GetTclStart(key);
        }
        
        public void PauseEvents(bool bwait) {
            base.Channel.PauseEvents(bwait);
        }
        
        public void PauseTests(bool bwait) {
            base.Channel.PauseTests(bwait);
        }
        
        public string BladeFilePath() {
            return base.Channel.BladeFilePath();
        }
        
        public string FactFilePath() {
            return base.Channel.FactFilePath();
        }
        
        public string GradeFilePath() {
            return base.Channel.GradeFilePath();
        }
        
        public string FirmwareFilePath() {
            return base.Channel.FirmwareFilePath();
        }
        
        public string CountsFilePath() {
            return base.Channel.CountsFilePath();
        }
        
        public void LogInValue(int setValue) {
            base.Channel.LogInValue(setValue);
        }
        
        public uint Connect(string UserID, string Password, string ComputerName) {
            return base.Channel.Connect(UserID, Password, ComputerName);
        }
        
        public void Initialize(string Key) {
            base.Channel.Initialize(Key);
        }
        
        public string Ping(string message) {
            return base.Channel.Ping(message);
        }
        
        public void Disconnect(string Key) {
            base.Channel.Disconnect(Key);
        }
        
        public bool Abort(string Reason, bool Force) {
            return base.Channel.Abort(Reason, Force);
        }
        
        public void StartTest(string ParseString, string TestName, string GradeName, string tableStr) {
            base.Channel.StartTest(ParseString, TestName, GradeName, tableStr);
        }
        
        public void SetConfig(string NewConfig) {
            base.Channel.SetConfig(NewConfig);
        }
        
        public void GetConfig(string TestName) {
            base.Channel.GetConfig(TestName);
        }
        
        public bool DelConfig(string Key, string TestName) {
            return base.Channel.DelConfig(Key, TestName);
        }
        
//         public Hitachi.Tester.Module.FileNameStruct[] DirConfig(string FileName) {
//             return base.Channel.DirConfig(FileName);
//         }
        
        public bool CopyFileOnBlade(string fromFile, string toFile) {
            return base.Channel.CopyFileOnBlade(fromFile, toFile);
        }
        
        public string GetConfigCRC(string TestName) {
            return base.Channel.GetConfigCRC(TestName);
        }
        
//         public Hitachi.Tester.Module.FileNameStruct GetGradeCRCs(string TestName) {
//             return base.Channel.GetGradeCRCs(TestName);
//         }
        
        public string GetFileCRC(string TestName) {
            return base.Channel.GetFileCRC(TestName);
        }
        
        public void TclInput(string inputString, bool bToTv) {
            base.Channel.TclInput(inputString, bToTv);
        }
        
        public void TclCommand(string Command, bool bToTv) {
            base.Channel.TclCommand(Command, bToTv);
        }
        
//         public Hitachi.Tester.Module.TesterStateStruct GetModuleState() {
//             return base.Channel.GetModuleState();
//         }
        
//         public void SetModuleState(Hitachi.Tester.Module.TesterStateStruct testerState) {
//             base.Channel.SetModuleState(testerState);
//         }
        
        public void GetBunnyStatus() {
            base.Channel.GetBunnyStatus();
        }
        
        public Hitachi.Tester.Enums.MemsStateValues GetMemsState() {
            return base.Channel.GetMemsState();
        }
        
        public void SetCounts(string countsString) {
            base.Channel.SetCounts(countsString);
        }
        
        public int GetCountValue(string name) {
            return base.Channel.GetCountValue(name);
        }
        
        public void SetCountValue(string name, int value) {
            base.Channel.SetCountValue(name, value);
        }
        
        public void IncCountValue(string name) {
            base.Channel.IncCountValue(name);
        }
        
        public void SaveCounts() {
            base.Channel.SaveCounts();
        }
        
        public void ZeroCounts() {
            base.Channel.ZeroCounts();
        }
        
        public void ClearStats() {
            base.Channel.ClearStats();
        }
        
        public void UpdateStatValuesViaEvent(string[] what, long from, long to) {
            base.Channel.UpdateStatValuesViaEvent(what, from, to);
        }
        
        public void GetFirstLastIndexViaEvent() {
            base.Channel.GetFirstLastIndexViaEvent();
        }
        
        public void GetFromToViaEvent(long from, long to) {
            base.Channel.GetFromToViaEvent(from, to);
        }
        
        public void UpdateDgrValuesViaEvent(System.TimeSpan timeSpan) {
            base.Channel.UpdateDgrValuesViaEvent(timeSpan);
        }
        
//         public Hitachi.Tester.Module.FileNameStruct[] BladeFileDir(string path, string Filter) {
//             return base.Channel.BladeFileDir(path, Filter);
//         }
    }
}
