//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hitachi.Tester.Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Hitachi.Tester.Module", ConfigurationName="ServiceReference1.TesterObjectContract", CallbackContract=typeof(Hitachi.Tester.Client.ServiceReference1.TesterObjectContractCallback))]
    public interface TesterObjectContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/Connect", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/ConnectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/ConnectReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/ConnectSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        uint Connect(string userID, string password, string computerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/Disconnect", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/DisconnectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/DisconnectReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/DisconnectSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void Disconnect(string userID, string computerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/KeepAliveChannel", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/KeepAliveChannelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/KeepAliveChannelReceiverFaultDetailFau" +
            "lt", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/KeepAliveChannelSenderFaultDetailFault" +
            "", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        int KeepAliveChannel();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/PingAllEvent", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/PingAllEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PingAllEventReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PingAllEventSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        string PingAllEvent(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/BladeFileDir", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/BladeFileDirResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BladeFileDirReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BladeFileDirSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        WD.Tester.Module.FileNameStruct[] BladeFileDir(string path, string Filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/CopyFileOnBlade", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/CopyFileOnBladeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/CopyFileOnBladeReceiverFaultDetailFaul" +
            "t", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/CopyFileOnBladeSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        bool CopyFileOnBlade(string fromFile, string toFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/BladeDelFile", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/BladeDelFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BladeDelFileReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BladeDelFileSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        bool BladeDelFile(string Key, string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SafeRemoveBlade", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SafeRemoveBladeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SafeRemoveBladeReceiverFaultDetailFaul" +
            "t", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SafeRemoveBladeSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void SafeRemoveBlade();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/BunnyReInit", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/BunnyReInitResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BunnyReInitReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/BunnyReInitSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        bool BunnyReInit();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsType", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetMemsTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsTypeReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsTypeSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void SetMemsType(WD.Tester.Module.BunnyPinMotionType whichKind);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsOpenSensorType", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetMemsOpenSensorTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsOpenSensorTypeReceiverFaultDeta" +
            "ilFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsOpenSensorTypeSenderFaultDetail" +
            "Fault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void SetMemsOpenSensorType(WD.Tester.Module.BunnyPinMotionSensor whichKind);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsCloseSensorType", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetMemsCloseSensorTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsCloseSensorTypeReceiverFaultDet" +
            "ailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetMemsCloseSensorTypeSenderFaultDetai" +
            "lFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void SetMemsCloseSensorType(WD.Tester.Module.BunnyPinMotionSensor whichKind);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetModuleState", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetModuleStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetModuleStateReceiverFaultDetailFault" +
            "", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetModuleStateSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        WD.Tester.Module.TesterState GetModuleState();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetModuleState", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetModuleStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetModuleStateReceiverFaultDetailFault" +
            "", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetModuleStateSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void SetModuleState(WD.Tester.Module.TesterState testerState);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetBunnyStatus", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetBunnyStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetBunnyStatusReceiverFaultDetailFault" +
            "", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetBunnyStatusSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void GetBunnyStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetMemsStatus", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetMemsStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetMemsStatusReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetMemsStatusSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        WD.Tester.Enums.MemsStateValues GetMemsStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetStrings", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetStringsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetStringsReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetStringsSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void SetStrings(string key, string[] names, string[] strings);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetStrings", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetStringsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetStringsReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetStringsSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        string[] GetStrings(string key, string[] names);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetIntegers", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetIntegersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetIntegersReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetIntegersSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void SetIntegers(string key, string[] names, int[] numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetIntegers", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetIntegersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetIntegersReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetIntegersSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        int[] GetIntegers(string key, string[] names);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/PinMotionToggle", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/PinMotionToggleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PinMotionToggleReceiverFaultDetailFaul" +
            "t", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PinMotionToggleSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void PinMotionToggle();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetFileCRC", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetFileCRCResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetFileCRCReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetFileCRCSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        string GetFileCRC(string TestName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/Name", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/NameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/NameReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/NameSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        string Name();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetConfig", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetConfigResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetConfigReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetConfigSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void SetConfig(string NewConfig);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetConfig", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetConfigResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetConfigReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetConfigSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void GetConfig(string TestName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/DelConfig", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/DelConfigResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/DelConfigReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/DelConfigSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        bool DelConfig(string Key, string TestName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/DirConfig", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/DirConfigResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/DirConfigReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/DirConfigSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        WD.Tester.Module.FileNameStruct[] DirConfig(string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/StartTest", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/StartTestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/StartTestReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/StartTestSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void StartTest(string ParseString, string TestName, string GradeName, string tableStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/PauseTests", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/PauseTestsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PauseTestsReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PauseTestsSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void PauseTests(bool bwait);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/hgst_get_servo", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/hgst_get_servoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_get_servoReceiverFaultDetailFault" +
            "", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_get_servoSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void hgst_get_servo(int index, int dev);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/hgst_move_servo", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/hgst_move_servoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_move_servoReceiverFaultDetailFaul" +
            "t", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_move_servoSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void hgst_move_servo(int index, int dev, int type, int end_pos, int max_vel, int accel);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/hgst_set_save_servo", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/hgst_set_save_servoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_set_save_servoReceiverFaultDetail" +
            "Fault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_set_save_servoSenderFaultDetailFa" +
            "ult", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void hgst_set_save_servo(int index, int dev, int type, int open_end_pos, int open_max_vel, int open_accel, int close_end_pos, int close_max_vel, int close_accel, int current_end_pos, int current_max_vel, int current_accel);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/hgst_get_neutral", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/hgst_get_neutralResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_get_neutralReceiverFaultDetailFau" +
            "lt", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_get_neutralSenderFaultDetailFault" +
            "", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void hgst_get_neutral(int index, int dev);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/hgst_set_neutral", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/hgst_set_neutralResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_set_neutralReceiverFaultDetailFau" +
            "lt", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_set_neutralSenderFaultDetailFault" +
            "", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void hgst_set_neutral(int index, int dev, int i_neutral);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/hgst_usb_reset", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/hgst_usb_resetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_usb_resetReceiverFaultDetailFault" +
            "", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/hgst_usb_resetSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void hgst_usb_reset(int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetCounts", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetCountsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetCountsReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetCountsSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void SetCounts(string countsString);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetCountValue", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetCountValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetCountValueReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetCountValueSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        int GetCountValue(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetCountValue", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetCountValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetCountValueReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetCountValueSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void SetCountValue(string name, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/IncCountValue", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/IncCountValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/IncCountValueReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/IncCountValueSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void IncCountValue(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SaveCounts", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SaveCountsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SaveCountsReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SaveCountsSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void SaveCounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/ZeroCounts", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/ZeroCountsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/ZeroCountsReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/ZeroCountsSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void ZeroCounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/ClearCountsStats", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/ClearCountsStatsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/ClearCountsStatsReceiverFaultDetailFau" +
            "lt", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/ClearCountsStatsSenderFaultDetailFault" +
            "", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void ClearCountsStats();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/CountsGetFirstLastIndexViaEvent", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/CountsGetFirstLastIndexViaEventRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/CountsGetFirstLastIndexViaEventReceive" +
            "rFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/CountsGetFirstLastIndexViaEventSenderF" +
            "aultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void CountsGetFirstLastIndexViaEvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/CountsGetFromToViaEvent", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/CountsGetFromToViaEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/CountsGetFromToViaEventReceiverFaultDe" +
            "tailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/CountsGetFromToViaEventSenderFaultDeta" +
            "ilFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void CountsGetFromToViaEvent(long from, long to);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/CountsUpdateDgrValuesViaEvent", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/CountsUpdateDgrValuesViaEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/CountsUpdateDgrValuesViaEventReceiverF" +
            "aultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/CountsUpdateDgrValuesViaEventSenderFau" +
            "ltDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void CountsUpdateDgrValuesViaEvent(System.TimeSpan timeSpan);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/InitializeTCL", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/InitializeTCLResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/InitializeTCLReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/InitializeTCLSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void InitializeTCL(string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/AbortTCL", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/AbortTCLResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/AbortTCLReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/AbortTCLSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        bool AbortTCL(string Reason, bool Force);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/TclInput", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/TclInputResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/TclInputReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/TclInputSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void TclInput(string inputString, bool bToTv);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/TclCommand", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/TclCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/TclCommandReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/TclCommandSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void TclCommand(string Command, bool bToTv);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/GetDataViaEvent", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/GetDataViaEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetDataViaEventReceiverFaultDetailFaul" +
            "t", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/GetDataViaEventSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void GetDataViaEvent(string[] names);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/PauseEvents", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/PauseEventsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PauseEventsReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/PauseEventsSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void PauseEvents(bool bwait);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/StaticTalkLogInValue", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/StaticTalkLogInValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/StaticTalkLogInValueReceiverFaultDetai" +
            "lFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/StaticTalkLogInValueSenderFaultDetailF" +
            "ault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void StaticTalkLogInValue(int setValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hitachi.Tester.Module/TesterObjectContract/SetLcdText", ReplyAction="Hitachi.Tester.Module/TesterObjectContract/SetLcdTextResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.ReceiverFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetLcdTextReceiverFaultDetailFault", Name="ReceiverFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        [System.ServiceModel.FaultContractAttribute(typeof(WD.Tester.Module.SenderFaultDetail), Action="Hitachi.Tester.Module/TesterObjectContract/SetLcdTextSenderFaultDetailFault", Name="SenderFaultDetail", Namespace="http://schemas.datacontract.org/2004/07/WD.Tester.Module")]
        void SetLcdText(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TesterObjectContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="Hitachi.Tester.Module/TesterObjectContract/BladeEventCallback")]
        void BladeEventCallback(WD.Tester.Module.BladeEventArgs e);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TesterObjectContractChannel : Hitachi.Tester.Client.ServiceReference1.TesterObjectContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TesterObjectContractClient : System.ServiceModel.DuplexClientBase<Hitachi.Tester.Client.ServiceReference1.TesterObjectContract>, Hitachi.Tester.Client.ServiceReference1.TesterObjectContract {
        
        public TesterObjectContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TesterObjectContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TesterObjectContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TesterObjectContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TesterObjectContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public uint Connect(string userID, string password, string computerName) {
            return base.Channel.Connect(userID, password, computerName);
        }
        
        public void Disconnect(string userID, string computerName) {
            base.Channel.Disconnect(userID, computerName);
        }
        
        public int KeepAliveChannel() {
            return base.Channel.KeepAliveChannel();
        }
        
        public string PingAllEvent(string message) {
            return base.Channel.PingAllEvent(message);
        }
        
        public WD.Tester.Module.FileNameStruct[] BladeFileDir(string path, string Filter) {
            return base.Channel.BladeFileDir(path, Filter);
        }
        
        public bool CopyFileOnBlade(string fromFile, string toFile) {
            return base.Channel.CopyFileOnBlade(fromFile, toFile);
        }
        
        public bool BladeDelFile(string Key, string FileName) {
            return base.Channel.BladeDelFile(Key, FileName);
        }
        
        public void SafeRemoveBlade() {
            base.Channel.SafeRemoveBlade();
        }
        
        public bool BunnyReInit() {
            return base.Channel.BunnyReInit();
        }
        
        public void SetMemsType(WD.Tester.Module.BunnyPinMotionType whichKind) {
            base.Channel.SetMemsType(whichKind);
        }
        
        public void SetMemsOpenSensorType(WD.Tester.Module.BunnyPinMotionSensor whichKind) {
            base.Channel.SetMemsOpenSensorType(whichKind);
        }
        
        public void SetMemsCloseSensorType(WD.Tester.Module.BunnyPinMotionSensor whichKind) {
            base.Channel.SetMemsCloseSensorType(whichKind);
        }
        
        public WD.Tester.Module.TesterState GetModuleState() {
            return base.Channel.GetModuleState();
        }
        
        public void SetModuleState(WD.Tester.Module.TesterState testerState) {
            base.Channel.SetModuleState(testerState);
        }
        
        public void GetBunnyStatus() {
            base.Channel.GetBunnyStatus();
        }
        
        public WD.Tester.Enums.MemsStateValues GetMemsStatus() {
            return base.Channel.GetMemsStatus();
        }
        
        public void SetStrings(string key, string[] names, string[] strings) {
            base.Channel.SetStrings(key, names, strings);
        }
        
        public string[] GetStrings(string key, string[] names) {
            return base.Channel.GetStrings(key, names);
        }
        
        public void SetIntegers(string key, string[] names, int[] numbers) {
            base.Channel.SetIntegers(key, names, numbers);
        }
        
        public int[] GetIntegers(string key, string[] names) {
            return base.Channel.GetIntegers(key, names);
        }
        
        public void PinMotionToggle() {
            base.Channel.PinMotionToggle();
        }
        
        public string GetFileCRC(string TestName) {
            return base.Channel.GetFileCRC(TestName);
        }
        
        public string Name() {
            return base.Channel.Name();
        }
        
        public void SetConfig(string NewConfig) {
            base.Channel.SetConfig(NewConfig);
        }
        
        public void GetConfig(string TestName) {
            base.Channel.GetConfig(TestName);
        }
        
        public bool DelConfig(string Key, string TestName) {
            return base.Channel.DelConfig(Key, TestName);
        }
        
        public WD.Tester.Module.FileNameStruct[] DirConfig(string FileName) {
            return base.Channel.DirConfig(FileName);
        }
        
        public void StartTest(string ParseString, string TestName, string GradeName, string tableStr) {
            base.Channel.StartTest(ParseString, TestName, GradeName, tableStr);
        }
        
        public void PauseTests(bool bwait) {
            base.Channel.PauseTests(bwait);
        }
        
        public void hgst_get_servo(int index, int dev) {
            base.Channel.hgst_get_servo(index, dev);
        }
        
        public void hgst_move_servo(int index, int dev, int type, int end_pos, int max_vel, int accel) {
            base.Channel.hgst_move_servo(index, dev, type, end_pos, max_vel, accel);
        }
        
        public void hgst_set_save_servo(int index, int dev, int type, int open_end_pos, int open_max_vel, int open_accel, int close_end_pos, int close_max_vel, int close_accel, int current_end_pos, int current_max_vel, int current_accel) {
            base.Channel.hgst_set_save_servo(index, dev, type, open_end_pos, open_max_vel, open_accel, close_end_pos, close_max_vel, close_accel, current_end_pos, current_max_vel, current_accel);
        }
        
        public void hgst_get_neutral(int index, int dev) {
            base.Channel.hgst_get_neutral(index, dev);
        }
        
        public void hgst_set_neutral(int index, int dev, int i_neutral) {
            base.Channel.hgst_set_neutral(index, dev, i_neutral);
        }
        
        public void hgst_usb_reset(int index) {
            base.Channel.hgst_usb_reset(index);
        }
        
        public void SetCounts(string countsString) {
            base.Channel.SetCounts(countsString);
        }
        
        public int GetCountValue(string name) {
            return base.Channel.GetCountValue(name);
        }
        
        public void SetCountValue(string name, int value) {
            base.Channel.SetCountValue(name, value);
        }
        
        public void IncCountValue(string name) {
            base.Channel.IncCountValue(name);
        }
        
        public void SaveCounts() {
            base.Channel.SaveCounts();
        }
        
        public void ZeroCounts() {
            base.Channel.ZeroCounts();
        }
        
        public void ClearCountsStats() {
            base.Channel.ClearCountsStats();
        }
        
        public void CountsGetFirstLastIndexViaEvent() {
            base.Channel.CountsGetFirstLastIndexViaEvent();
        }
        
        public void CountsGetFromToViaEvent(long from, long to) {
            base.Channel.CountsGetFromToViaEvent(from, to);
        }
        
        public void CountsUpdateDgrValuesViaEvent(System.TimeSpan timeSpan) {
            base.Channel.CountsUpdateDgrValuesViaEvent(timeSpan);
        }
        
        public void InitializeTCL(string Key) {
            base.Channel.InitializeTCL(Key);
        }
        
        public bool AbortTCL(string Reason, bool Force) {
            return base.Channel.AbortTCL(Reason, Force);
        }
        
        public void TclInput(string inputString, bool bToTv) {
            base.Channel.TclInput(inputString, bToTv);
        }
        
        public void TclCommand(string Command, bool bToTv) {
            base.Channel.TclCommand(Command, bToTv);
        }
        
        public void GetDataViaEvent(string[] names) {
            base.Channel.GetDataViaEvent(names);
        }
        
        public void PauseEvents(bool bwait) {
            base.Channel.PauseEvents(bwait);
        }
        
        public void StaticTalkLogInValue(int setValue) {
            base.Channel.StaticTalkLogInValue(setValue);
        }
        
        public void SetLcdText(string text) {
            base.Channel.SetLcdText(text);
        }
    }
}
